### ISSUE TITLE
Can't recognize the plugin

### ISSUE THREAD

**Issue by robertlzj** [syroezhkin/VsDottedLine#1] opened 2017-08-28 07:47 UTC
Hi,

Using default install method. Can't recognize the plugin on the latest SketchUp Pro 2017 17.2.2555 64bit with Chinese language in Win10 64bit. (Application path contain only ANSI characters showing bellow)
Change file name to _vs_dotted_line.rb_ (should remove 'z' from the '.rbz'?) is helpless.

If place the file _vs_dotted_line.rb_ under _SketchUp\Plugins_ will get "Load Errors" dialog when running SketchUp, shows:

> Error: #<SyntaxError: C:/Users/RobertLin/AppData/Roaming/SketchUp/SketchUp 2017/SketchUp/Plugins/vs_dotted_line.rb:1: Invalid char `\x03' in expression>

**Comment by syroezhkin** [comment] 2017-08-28 12:30
Hi!
Thank you for the report! While I'm trying to reproduce and fix this issue, you can try to install the plugin manually. Just rename .rbz to .zip and extract its files to standard SketchUp plugin directory. Or try previous [version 1.0.1](https://github.com/syroezhkin/VsDottedLine/releases/tag/v.1.0.1).

**Comment by syroezhkin** [comment] 2017-08-28 20:05
So, I've made some changes in plugin registration file. Now the root path encode in UTF-8. Seems it may fix the bug. But I need your help in testing. Could you inform me if everything works or not? You can find new plugin files in this [branch](https://github.com/syroezhkin/VsDottedLine/tree/Plugin-install-bug):

**Comment by robertlzj** [comment] 2017-08-29 00:16
New version works fine now. Thank you~
Maybe it's my fault from the very beginning, to rename .rbz to .rb directly. I'm not realize .rbz is Ruby's compress package.

**Comment by syroezhkin** [comment] 2017-08-30 15:14
Excellent! Actually there were some problems because in the past I received a bug that close to yours from one another user. So I close this issue and roll out the new version. Thanks again!

**Closed as completed** 2017-08-30 15:14 UTC
Labels: bug
